CREATE DATABASE salvadora;

SHOW DATABASES; -- muestra todas las bases de datos

USE salvadora;

CREATE TABLE CLIENTE (
    CI INT (10) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO VARCHAR(20) NOT NULL,
    DIRECCION TEXT(50),
    TELEFONO INT(8),
    PRIMARY KEY (CI)
);


CREATE TABLE PROVEEDOR (
	ID_PROVEEDOR INT NOT NULL,
    NOMBRE VARCHAR(45) NULL,
    DIRECCION VARCHAR(45) NULL,
    TELEFONO INT(10) NULL,
    PRIMARY KEY (ID_PROVEEDOR)
);

SELECT * FROM PROVEEDOR;

CREATE TABLE PRODUCTO(
	COD_PRODUCTO INT(15) PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(22),
    MARCA VARCHAR(22),
    COLOR VARCHAR(22),
    STOCK INT(100),
    PRECIO FLOAT
)AUTO_INCREMENT = 100; -- el auto_increment: empieza en 100

SHOW TABLES;

-- agregar columna MODELO despues de COLOR
ALTER TABLE PRODUCTO
    ADD COLUMN MODELO VARCHAR(15) AFTER COLOR;

CREATE TABLE COMPRA(
	CI INT(13) NOT NULL,
    COD_PRODUCTO INT(15) NOT NULL,
    FECHA_COMPRA DATE,
    CANTIDAD INT(100),
    PRIMARY KEY (CI, COD_PRODUCTO)
);

SELECT * FROM COMPRA;

CREATE TABLE PROVEE (
	ID_PROVEEDOR INT(10) NOT NULL,
    COD_PRODUCTO INT(15) NOT NULL,
    FECHA DATE,
    CANTIDAD INT(100),
    PRIMARY KEY (ID_PROVEEDOR, COD_PRODUCTO)
);

DESCRIBE cliente; --muestra la estructura de la tabla
SHOW TABLES; -- muestra todas las tablas de salvadora;

INSERT INTO CLIENTE (CI,NOMBRE,APELLIDO,DIRECCION,TELEFONO)
    VALUE(335287,'Victor','Cruz','calle 4 z. Miraflores',77850451);

INSERT INTO CLIENTE (CI,NOMBRE,APELLIDO,DIRECCION,TELEFONO)
	VALUE(789564,'Victoria','Zarate','calle Las Begonias,  Miraflores',89750455);


DELETE FROM CLIENTE; -- elimina todos los registros de la tabla cliente


--insert datos a PRODUCTO
INSERT INTO PRODUCTO (COD_PRODUCTO,NOMBRE,MARCA,COLOR,MODELO,STOCK,PRECIO)
VALUES
(101, 'TOSTADORA','OSTER','ROJO','RT-8',34,1200),
(NULL,'LAVADORA','LG','GRIS','RT-7',20,23000);